# Generated by Django 3.1.1 on 2020-09-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magiclinkcredential',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
    ]
